// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_-9kIATw8uGb266_Y6IsoBRgDMmyWpw',
    appId: '1:103297231950:web:85baef4518db84316e671f',
    messagingSenderId: '103297231950',
    projectId: 'beerecipe-1c4db',
    authDomain: 'beerecipe-1c4db.firebaseapp.com',
    storageBucket: 'beerecipe-1c4db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8FyZrbhz4GofLGnUCOh4-0weQJRZP83I',
    appId: '1:103297231950:android:4f5ee1526ce2237f6e671f',
    messagingSenderId: '103297231950',
    projectId: 'beerecipe-1c4db',
    storageBucket: 'beerecipe-1c4db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1G44YiW1u_4xwaA_kOxNGHE3UsBnjvHM',
    appId: '1:103297231950:ios:b44f04cc875ab2526e671f',
    messagingSenderId: '103297231950',
    projectId: 'beerecipe-1c4db',
    storageBucket: 'beerecipe-1c4db.firebasestorage.app',
    iosBundleId: 'com.example.beerecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1G44YiW1u_4xwaA_kOxNGHE3UsBnjvHM',
    appId: '1:103297231950:ios:b44f04cc875ab2526e671f',
    messagingSenderId: '103297231950',
    projectId: 'beerecipe-1c4db',
    storageBucket: 'beerecipe-1c4db.firebasestorage.app',
    iosBundleId: 'com.example.beerecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6_-9kIATw8uGb266_Y6IsoBRgDMmyWpw',
    appId: '1:103297231950:web:4d7e3cb9af7192506e671f',
    messagingSenderId: '103297231950',
    projectId: 'beerecipe-1c4db',
    authDomain: 'beerecipe-1c4db.firebaseapp.com',
    storageBucket: 'beerecipe-1c4db.firebasestorage.app',
  );
}
